#!/bin/sh

# Stop child processes before exiting
trap "pkill -P $$" EXIT

# Load resources if available
loadresources () {
	[ $# -eq 1 ] && [ -f "$1" ] && xrdb -merge "$1"
}

# Load keymap modifications if available
modifykeymap () {
	[ $# -eq 1 ] && [ -f "$1" ] && xmodmap "$1"
}

# Start program in background if available
launch () {
	if [ $# -eq 1 ] && [ -x $(command -v "$1") ]; then
		"$1" &
	fi
}

loadresources /etc/X11/xinit/.Xresources
loadresources $HOME/.Xresources

modifykeymap /etc/X11/xinit/.Xmodmap
modifykeymap $HOME/.Xmodmap

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
 	done
	unset f
fi

# Autostart
launch wallpaper.sh
launch sxhkd
launch lxpolkit
launch udiskie

# Update status bar periodically
while true; do
	xsetroot -name "$(date '+ %a %-d %b %R')"
	sleep 5
done &

exec dwm
