#!/bin/sh

# Stop child processes before exiting
trap "pkill -P $$" EXIT

# Load settings for colors, fonts, etc.
xrdb -merge .Xresources

# Required to start dunst with systemd if there is no display manager
systemctl --user import-environment DISPLAY

# Load wallpaper
$HOME/.fehbg &

udiskie &

# Update status bar regularly
while true
do
	xsetroot -name "$(date '+ %a %-d %b %R')"
	sleep 10
done &

exec dwm
