#!/bin/sh

# Stop child processes before exiting
trap "pkill -P $$" EXIT

# Autostart

lxsession &
wallpaper.sh &
sxhkd &

# Update status bar periodically
while true; do
    xsetroot -name "$(date '+ %a %-d %b %R')"
    sleep 10
done &
