#!/bin/sh

monitor=($(bspc query -M --names))

if [ "${#monitor[@]}" -gt 1 ]; then
	bspc monitor "${monitor[0]}" -d 1 2 3 4
	bspc monitor "${monitor[1]}" -d 5 6 7 8
else
	bspc monitor -d 1 2 3 4 5 6
fi

bspc config border_width          2
bspc config window_gap            5
bspc config focused_border_color  "#fabd2f"
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Pavucontrol state=floating
bspc rule -a Zathura state=tiled

# Autostart

launch () {
	local p=$(which "$1")
	if [ "$?" -eq 0 ] && [ -x "$p" ]; then
		killall -q "$1"
		"$@" &
	fi
}

launch polybar main
launch sxhkd
launch udiskie --tray
launch dropbox
launch pasystray
