#!/bin/sh

# Stop child processes before exiting
trap "pkill -P $$" EXIT

# Load resources if available
loadresources() {
	while [ "$#" != "0" ]; do
		[ -f "$1" ] && xrdb -merge "$1"
		shift
	done
}

# Load keymap modifications if available
modifykeymap() {
	while [ "$#" != "0" ]; do
		[ -f "$1" ] && xmodmap "$1"
		shift
	done
}

# Start programs in background if available
launch() {
	if [ "$#" != "0" ] && [ $(command -v "$1" 2>/dev/null) ]; then
		"$@" &
	fi
}

loadresources /etc/X11/xinit/.Xresources $HOME/.Xresources

modifykeymap /etc/X11/xinit/.Xmodmap $HOME/.Xmodmap

# Autostart

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
 	done
	unset f
fi

launch wallpaper.sh
launch sxhkd

systemctl --user start redshift.service

# Update status bar periodically
while true; do
	xsetroot -name "$(date '+ %a %-d %b %R')"
	sleep 10
done &

exec dwm
